# -*- coding: utf-8 -*-
"""TS_Airpassengers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3hkn0sDUQVXH7zn0iqaBADtGSOUu3ZQ

##**Importing Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('AirPassengers.csv')

df.head()

"""##**EDA**"""

df.info()

df.shape

df['Month']=pd.to_datetime(df['Month'])

df.info()

df.isnull().sum().sum()

df.duplicated().sum()

df.index=df['Month']

df.drop('Month',axis=1,inplace=True)

df.info()

df

"""##**Vizualizing the data**"""

df.plot()

"""##**Adfuller Test**"""

#adf --> Adfuller test
#H0 --> data is stationary
#H1 --> data is not stationary

from statsmodels.tsa.stattools import adfuller

result=adfuller(df['#Passengers'])

result

p_val=result[1]
p_val

if(p_val<0.05):
  print("Accept the null hypothesis,The time Series data is stationary")
else:
  print("Accept the alternate hynothesis,The Time series data is not stationary")

"""##**Differencing**"""

rolling_mean=df.rolling(window=12).mean()

rolling_mean.head(12)

df_detrended=df-rolling_mean

df_detrended

ax1=plt.subplot(1,2,1)
df.plot(figsize=(12,4),color='tab:red',title='Original Data',ax=ax1)

ax2=plt.subplot(1,2,2)
df_detrended.plot(figsize=(12,4),color='tab:blue',title='Detrended Data',ax=ax2)

df_detrended.dropna(inplace=True)

result=adfuller(df_detrended['#Passengers'])

result

p_val=result[1]

if p_val<0.05:
  print("Accept the null hypothesis,The time Series data is stationary")
else:
  print("Accept the alternate hynothesis,The Time series data is not stationary")

"""##**Plotting the stationary data to check**"""

m=df_detrended.rolling(window=12).mean()
s=df_detrended.rolling(window=12).std()

plt.plot(df_detrended,color='tab:red',label='Original')
plt.plot(m,color='tab:blue',label='Rolling Mean')
plt.plot(s,color='tab:green',label='Rolling Std')
plt.title('Stationary data check using plot')
plt.show()

"""##**Model Building**"""

train=df_detrended[:120]['#Passengers']
test=df_detrended[120:]['#Passengers']

train

test

from statsmodels.tsa.arima.model import ARIMA

model=ARIMA(train,order=(1,0,2))
model_fit=model.fit()

df_detrended['Predicted']=model_fit.predict(start=len(train),end=len(train)+len(test)-1)

df_detrended

df_detrended[['#Passengers','Predicted']].plot()

"""##**auto_arima**"""

#!pip install numpy==1.26.4 scipy==1.14.1

!pip install pmdarima

from pmdarima import auto_arima

auto=auto_arima(df_detrended['#Passengers'])

auto.summary()

from statsmodels.tsa.statespace.sarimax import SARIMAX

model=SARIMAX(train,order=(3,0,2),seasonal_order=(3,0,2,12))
model_fit=model.fit()

df_detrended['Predicted']=model_fit.predict(start=len(train),end=len(train)+len(test)-1)

df_detrended[['#Passengers','Predicted']].plot()

forecast=model_fit.get_forecast(steps=24) #test+predicting years
future_preds=forecast.predicted_mean

df_detrended.plot()
future_preds.plot()