# -*- coding: utf-8 -*-
"""Netflix_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAaSKERVJFvJWZ51ts0ddCs2_M3WXufH

##**Importing Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

netflix_dataset=pd.read_csv('/content/drive/MyDrive/netflix_recommendation_system(SVD)/Copy of combined_data_1.txt.zip',header=None,names=['Cust_Id','Ratings'],usecols=[0,1])

netflix_dataset

"""##**EDA**"""

netflix_dataset.isnull().sum()

movie_count=netflix_dataset.isnull().sum()
movie_count=movie_count['Ratings']
movie_count

total_count=netflix_dataset['Cust_Id'].nunique()

customer_count=total_count-movie_count
customer_count

ratings_count=netflix_dataset['Cust_Id'].count()-movie_count
ratings_count

Stars=netflix_dataset['Ratings'].value_counts()

Stars

movie_id=None
movie_np=[]

for customer in netflix_dataset['Cust_Id']:
  if ":" in customer:
    movie_id=int(customer.replace(":","")) #1:-->1
  movie_np.append(movie_id)

netflix_dataset['Movie_id']=movie_np

netflix_dataset

netflix_dataset.dropna(inplace=True)

netflix_dataset

netflix_dataset.info()

netflix_dataset['Cust_Id']=netflix_dataset['Cust_Id'].astype(int)

netflix_dataset.info()

movie_review_count=netflix_dataset['Movie_id'].value_counts()
movie_review_count

bench_mark=round(movie_review_count.quantile(0.6),0)
bench_mark

drop_movie_index=movie_review_count[movie_review_count<bench_mark].index

drop_movie_index

len(drop_movie_index)

movie_customer_count=netflix_dataset['Cust_Id'].value_counts()
movie_customer_count

bench_mark_cust=round(movie_customer_count.quantile(0.6),0)

bench_mark_cust

drop_cust_index=movie_customer_count[movie_customer_count<bench_mark_cust].index

drop_cust_index

netflix_dataset=netflix_dataset[~netflix_dataset['Movie_id'].isin(drop_movie_index)]
netflix_dataset=netflix_dataset[~netflix_dataset['Cust_Id'].isin(drop_cust_index)]

netflix_dataset

"""##**Model Building**"""

movie_titles=pd.read_csv("/content/drive/MyDrive/netflix_recommendation_system(SVD)/Copy of movie_titles.csv",encoding='ISO-8859-1',header=None,names=['Movie_Id','Year','Name'],usecols=[0,1,2])

movie_titles

!pip install numpy==1.26.4

!pip install scikit-surprise

"""| Component        | Purpose                                                                                   |
| ---------------- | ----------------------------------------------------------------------------------------- |
| `SVD`            | Matrix Factorization algorithm — one of the most popular collaborative filtering models.  |
| `Reader`         | Defines the format of your rating data (e.g., rating scale 1–5, file type, column order). |
| `Dataset`        | Loads your data into a Surprise-compatible structure.                                     |
| `cross_validate` | Performs model evaluation using k-fold cross-validation (like in scikit-learn).           |

-fold cross-validation as an example (used in cross_validate()):

Split dataset into k equal parts (called folds).
Example: For 5-fold CV → data is split into 5 subsets.

Perform k iterations of training/testing:

In each iteration:

Use k-1 folds for training.

Use 1 fold for testing.

Rotate the test fold each time.

Compute your evaluation metric (e.g., RMSE, MAE, Accuracy) for each fold.

Average all the metric values — that’s your final performance score.

| Fold | Training Data | Testing Data | RMSE (Example) |
| ---- | ------------- | ------------ | -------------- |
| 1    | Folds 2–5     | Fold 1       | 0.88           |
| 2    | Folds 1,3–5   | Fold 2       | 0.84           |
| 3    | Folds 1–2,4–5 | Fold 3       | 0.86           |
| 4    | Folds 1–3,5   | Fold 4       | 0.85           |
| 5    | Folds 1–4     | Fold 5       | 0.87           |
"""

from surprise import SVD,Reader,Dataset,accuracy
from surprise.model_selection import cross_validate

reader=Reader()

data=Dataset.load_from_df(netflix_dataset[['Movie_id','Cust_Id','Ratings']][:100000],reader)

data

model=SVD()

#Cross Validation
cross_validate(model,data,measures=['RMSE'],cv=3)

#select a single user for recommending

user_rating=netflix_dataset[netflix_dataset['Cust_Id']==1331154]
user_rating

#creating the duplicate copy of movie_titles

user_1331154=movie_titles.copy()
user_1331154

user_1331154=user_1331154[~ user_1331154['Movie_Id'].isin(drop_movie_index)]

user_1331154 #after removing the movies in drop_movie_index

user_1331154['Estimated']=user_1331154['Movie_Id'].apply(lambda x: model.predict(1331154,x).est)

user_1331154

user_1331154.sort_values('Estimated',ascending=False)

user_1331154.head()





































